luci-app-passwall_INCLUDE_Xray
luci-app-passwall_INCLUDE_Hysteria
luci-app-passwall_INCLUDE_SingBox
luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client
luci-app-passwall_INCLUDE_V2ray_Geodata
luci-app-passwall_INCLUDE_V2ray_Geoview
luci-app-passwall_INCLUDE_tuic_client
luci-app-socat
luci-mod-network
kmod-usb-storage
kmod-fs-ext4
kmod-fs-vfat
kmod-fs-exfat
kmod-fs-ntfs
fdisk
luci-app-autoreboot
luci-app-frpc
luci-app-openvpn-server
luci-app-openvpn
luci-app-scutclient
luci-app-ddns
luci-app-openclash
luci-app-passwall
luci-app-tailscale
luci-app-ttyd
luci-app-vlmcsd
luci-app-wireguard
xl2tpd
scut-unicom
bind-host
